### ISSUE TITLE
LDAP issue with java error

### ISSUE THREAD

**Issue by priyankade** [dwimberger/crowd-ldap-server#28]
Will this work with JRE 9?

Getting java error:
Error when running command : >>    ./run.sh
[12:15:41] INFO [net.wimpi.crowd.ldap.CrowdLDAPServer] - Configuration directory: /opt/crowd-ldap-server/etc
[12:15:41] INFO [net.wimpi.crowd.ldap.CrowdLDAPServer] - Starting up CrowdLDAP Server
[12:15:41] INFO [net.wimpi.crowd.ldap.CrowdLDAPServer] - Working directory: /opt/crowd-ldap-server/work
[12:15:41] DEBUG [net.wimpi.crowd.ldap.CrowdLDAPServer] - Loading configuration.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at com.atlassian.crowd.integration.rest.service.factory.RestCrowdClientFactory.newInstance(RestCrowdClientFactory.java:66)
        at net.wimpi.crowd.ldap.CrowdLDAPServer.initCrowdClient(CrowdLDAPServer.java:211)
        at net.wimpi.crowd.ldap.CrowdLDAPServer.<init>(CrowdLDAPServer.java:114)
        at net.wimpi.crowd.ldap.CrowdLDAPServer.main(CrowdLDAPServer.java:392)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more

**Comment by priyankade** [comment]
Was able to fix this issue by adding the <dependency> in pom.xml for maven build.
<dependency>
                        <groupId>javax.activation</groupId>
                        <artifactId>javax.activation-api</artifactId>
                        <version>1.2.0</version>
                </dependency>
                <dependency>
                        <groupId>org.glassfish.jaxb</groupId>
                        <artifactId>jaxb-runtime</artifactId>
                        <version>2.3.2</version>
                </dependency>
                <dependency>
                        <groupId>javax.xml.bind</groupId>
                        <artifactId>jaxb-api</artifactId>
                        <version>2.3.1</version>
                </dependency>
                <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-core</artifactId>
                        <version>2.2.11</version>
                </dependency>
                <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-impl</artifactId>
                        <version>2.2.11</version>
                </dependency>
